import type { Metadata } from "next";
import { Noto_Serif_Ethiopic } from "next/font/google";
import "@/app/globals.css";
import { Topbar, Subheader, Drawer, Main } from "@/components/layouts";

const inter = Noto_Serif_Ethiopic({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <Subheader />
        <section className="flex px-12 gap-11 mt-2 h-full">
          <Drawer />
          <Main>{children}</Main>
        </section>
      </body>
    </html>
  );
}
